# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/davia/EE2026 Labs/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/davia/EE2026 Labs/project_1/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/davia/EE2026 Labs/project_1/project_1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/Desktop/00.coe}}
add_files {{C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/Desktop/weights.coe}}
read_verilog {
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/alphabets.vh}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/new/char_dimensions.vh}
}
set_property file_type "Verilog Header" [get_files {{C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/alphabets.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/new/char_dimensions.vh}}]
read_verilog -library xil_defaultlib {
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/A_disp.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/new/Audio_Ball.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/new/Audio_Capture.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/new/Audio_Visualiser.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/B1_disp.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/B2_disp.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/B3_disp.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/BRAM_GroupMenu.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/mainmenu/BRAM_MainMenu.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/BRAM_codeScreen.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/BRAM_csgo.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/BRAM_messages.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/C2_disp.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/C3_disp.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/F1_disp.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/F2_disp.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/G1_disp.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/J2_disp.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/J3_disp.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/L2_disp.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/L3_disp.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/new/Led_Control.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/mainmenu/MainMenu.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/imports/Desktop/Oled_Display.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/new/Receiver.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/new/Top_Student.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/Top_Student.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/new/UART_task.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/new/as_display.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/blankchar.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/button_controls.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/new/d_ff.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/dff.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/display_control.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/new/draw_character.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/new/draw_on_oled.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/eastercode.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/encryption.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/enterLetter.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/homepage.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_A.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_B.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_C.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_D.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_F.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_G.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_H.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_I.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_J.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_K.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_L.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_M.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_N.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/learn_p1.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/letterCount.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/mainmenu/menuGreenBox.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/messages.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/new/oled_display_chat.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/new/process_bitmap.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/redBox.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/new/square_controls.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/steganography.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/new/stegoGreenBox.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/davia/EE2026 Labs/MODS/MODS/MODS.srcs/sources_1/new/variable_clock.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/new/variable_clock.v}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/new/top_module.v}
}
read_vhdl -library xil_defaultlib {
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/imports/Desktop/Mouse_Control.vhd}
  {C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/sources_1/imports/ntyythepro/Downloads/Telegram Desktop/anne.xpr/MODS/MODS.srcs/sources_1/imports/Desktop/Ps2Interface.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/constrs_1/new/constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/davia/EE2026 Labs/project_1/project_1.srcs/constrs_1/new/constraints.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_module -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
